openapi: 3.0.0

paths:
  /pets:
    get:
      summary: List pets

    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string

                age:
                  type: integer


  /pets/{id}:
    get:
      summary: Get pet
